library langService;

import 'dart:html';

bool isEng = false;

var dict = {
  'Prosodiya Online Text Analyse':'Prosodiya Online Text Analysis',
  'Aufbereitung von Texten zur LRS Therapie':'Preparation of texts for LRS therapy',
  'Textanalyse':'Textanalysis',
  'Nutzerkonto':'User account',
  'Betonungsdatenbank':'Linguistic database',
  'Einloggen oder Konto erstellen':'Log in or create an account',
  'Die Online Text Analyse wurde im Rahmen einer Masterarbeit entwickelt und im Rahmen einer Bachelorarbeit an der Universität Tübingen weiterentwickelt. Die App gibt die Möglichkeit beliebige Texte zu analysieren und aufzubereiten.':'The online text analysis was developed as part of a master thesis and further developed as part of bachelor thesis at the University of Tübingen. This App gives you the opportunity to analyze and edit any text.',
  'Die ursprüngliche Zielsetzung war dabei Silben und Betonungsmuster in Wörtern farblich hervorzuheben. So bearbeitete Texte werden von Lerntherapeuten für die Therapie von Lese-Rechtschreibschwäche (LRS) eingesetzt. Durch die Trennung und Hervorhebung einzelner Silben kann der Sprachrhythmus im Text besser wahrgenommen werden, somit wird das Textverständnis verbessert.':'The original goal was to emphasize syllables and stress patterns in words in color. So edited texts are used by learning therapists for the treatment of reading-spelling disorders. By separating and highlighting individual syllables, the linguistic rhythm in the text can be better perceived, thus the understanding of the text would be improved.',
  'Die App soll das Erstellen dieser Lerntexte vereinfachen. Im Vergleich einer manuellen Generierung der Texte, zum Beispiel mit einem Textverarbeitungsprogramm, geschieht das meiste automatisch. Bei Unklarheiten (z.B. unbekannte Wörter) wird der Nutzer durch eine übersichtliche Benutzerschnittstelle geleitet, um diese zu beseitigen. Durch die Verwendung von Nutzerkonten können Texte auch gespeichert werden, außerdem kann die globale Wort Datenbank erweitert werden.':'The app should simplify the creation of these learning texts. In comparison of a manual generation of the texts, for example with a word processing program, most of them are done automatically. In case of ambiguity (e.g. unknown Words), the user is guided through a clear user interface in order to eliminate them. By using user accounts, texts can also be saved, and the global word database can be extended.',
  'Zur Analyse kann einfach ein eigener Text eingegeben oder kopiert werden. Nachdem der Text analysiert wurde können unbekannte Wörter geklärt und die Anzeigeeinstellungen angepasst werden. Es stehen außerdem Funktionen zum Drucken oder Kopieren (Weiterverwendung in Textverarbeitungsprogramm) zur Verfügung.':'For analysis, you can simply enter your own text or copy it. After the text is analyzed unknown words can be clarified and the display settings can be adjusted. Printing or copying (reuse in word processor) the text is available as well.',
  'Zum effektiven Arbeiten mit der App wird ein Nutzerkonto benötigt. Dadurch lassen sich eigene Einträge für unbekannte Wörter erstellen sodass diese erkannt werden, wenn sie erneut vorkommen. Außerdem können verwendete Texte gespeichert und wiederverwendet werden.':'To work effectively with the app, a user account is required. This can be your own entries create unknown words so that they are recognized when they happen again. In addition, you can used texts are saved and reused.',
  'Das Herzstück der Textanalyse ist eine Datenbank in der Betonungsmuster und andere Worteigenschaften gespeichert sind. Wegen des immensen Umfangs eines Sprachwortschatzes sind nicht alle Wörter und Wortbeugungen der deutschen Sprache enthalten.':'The heart of the text analysis is a database where the stress patterns and other word properties are stored. Because of the immense scope of a vocabulary, not all words of the English language are included.',
  'Die Datenbank kann jedoch von allen Nutzern erweitert werden. Wird ein unbekanntes Wort bei der Textanalyse hinzugefügt steht es nur dem Benutzer zur Verfügung, der den Eintrag erstellt hat. Um es allen Nutzern bereitzustellen, muss es von mindestens zwei weiteren Nutzern bestätigt werden. Auf der Seite':'However, the database can be extended by all users. If there is an unknown word in the text analysis and a user add the word, it is only available for the user. In order to be available for all users, it must be confirmed by at least two other users. On the ',
  'Verifizierung':'Verification',
  'kann jeder Nutzer Wörter bestätigen oder Gegenvorschläge einbringen. So kann die Datenbank wachsen und mehr Wörter werden automatisch erkannt.':' page allows any user to confirm words or counterproposals. So the database can grow and more words become automatically recognized.',
  'Betonungsmuster':'Stress pattern',
  'betonte Silbe durch Klicken auswählen':'Select stressed syllable by clicking',
  'Silbentrennung':'Syllabication',
  'Silben mit "-" trennen':'Separate syllables with "-"',
  'Vorschläge Betonungsmuster und Silbentrennung':'Stress pattern and syllabication proposals',
  'Text Analyse':'Text Analysis',
  'Bitte geben Sie einen Text ein.':'Please enter a text.',
  'Analysiere':'Analyzing',
  'Neu analysieren':'Analyze',
  'Text speichern':'Save text',
  'Speichere den aktuellen Text, er kann dann auf der Benutzer Seite aufgerufen und wiederverwendet werden':'Save the current text, it can be accessed on the user page and reused',
  'Speichern':'Save',
  'Neu':'New',
  'Neuen Text eingeben':'Enter new text',
  'Aktuelle Analyse verwerfen und neuen Text eingeben':'Discard current analysis and enter new text',
  'Bitte Titel eingeben.':'Please enter a title.',
  'Bitte Text eingeben.':'Please enter a text.',
  'Text hinzugefügt.':'Text was successfully saved.',
  'Fehler beim speichern des Texts.':'Error saving text.',
  'Der Text konnte nicht analysiert werden.':'The text could not be analyzed.',
  'Der Text wurde erfolgreich analysiert und wird in der Vorschau hervorgehoben dargestellt. Sie können in der Vorschau jedes Wort bearbeiten, indem Sie darauf klicken.':'The text has been successfully parsed and will be highlighted in the preview. You can edit any word in the preview by clicking on it.',
  'Vorschau':'Preview',
  'Drucken':'Print',
  'Lesemodus':'Reading Mode',
  'Lesemodus beenden':'Exit Reading Mode',
  'Kopieren (Zwischenablage)':'Copy (Clipboard)',
  'Unbekannte Wörter klären':'Clarify unknown words',
  'oder direkt auf das Wort klicken':'or directly click on the word',
  'Keine unbekannten Wörter.':'No unknown words.',
  'Sie müssen eingeloggt sein, um Wörter hinzuzufügen.':'You must be logged in to add words.',
  'Fehler beim kopieren. Bitte markieren Sie den Text und kopieren diesen manuell (Strg+C).':'Error copying. Please mark the text and copy it manually (Strg+C).',
  'Der Text wurde in die Zwischenablage kopiert.':'The text has been copied to the clipboard.',
  'Einstellungen':'Settings',
  'Betonte Silbe':'Stressed syllables',
  'Unbetonte Silbe':'Unstressed syllables',
  'Wort Hintergrundfarbe':'Word background color',
  'Silbe hervorheben':'Highlight syllable',
  'Schriftgröße':'Font size',
  'Silbenabstand':'Syllable distance',
  'Wortabstand':'Word distance',
  'Zeilenabstand':'Line spacing',
  'Zeichenabstand':'Letter distance',
  'Silbentrennzeichen':'Hyphenation character',
  'Wortart':'Part of speech',
  'Vorlagen':'Template',
  'Klicke auf eine Vorlage in der Liste um sie auf den aktuellen Text anzuwenden':'Click on a template in the list to apply it to the current text',
  'Es gibt noch keine Vorlagen':'There are no text templates yet',
  'Vorlage speichern':'Save template',
  'Speichere die aktuelle Vorlage um sie wiederzuverwenden':'Save the current template to reuse it',
  'Vorlage konnte nicht gespeichert werden.':'Template could not be saved.',
  'Vorlage gespeichert.':'Template saved.',
  'Neue Vorlage konnte nicht angelegt werden.':'New template could not be created.',
  'Neue Vorlage angelegt.':'New template created.',
  'Vorlage konnte nicht gelöscht werden.':'Could not delete the template.',
  'Vorlage gelöscht.':'The template is deleted.',
  'Benutzen':'Use',
  'Neue Vorlage':'New template',
  'Fett':'Bold',
  'Schriftfarbe':'Letter color',
  'Hintergrundfarbe':'Background color',
  'Annotieren':'Annotate',
  'Unbetont':'Unstressed',
  'Ignorieren':'Ignore   ',
  'Nomen':'Noun',
  'Eigenname':'Proper noun',
  'Verb':'Verb',
  'Hilfsverb':'Modal verb',
  'Adjektiv':'Adjective',
  'Adverb':'Adverb',
  'Artikel':'Article',
  'Adposition':'Apposition',
  'Pronomen':'Pronoun',
  'Konjunktion':'Conjunction',
  'Zahl':'Numeral',
  'Partikel':'Particle',
  'Unbekannt':'Unknown',
  'Gleiche Wörter übernehmen':'Take over the same words',
  'Hallo':'Hello',
  'Neues Konto erstellen':'Open a new account',
  'Experte':'Expert',
  'Hier kannst Du gespeicherte Texte, manuelle Wörterbuch Einträge und Dein Konto verwalten':'You can manage saved texts, manual dictionary entries and your account here',
  'Benutzerkonto':'User account',
  'Logout erfolgreich.':'Logout successful.',
  'Konto löschen':'Delete user account',
  'Löschen':'Delete',
  'Fehler beim Kontolöschen. Versuchen Sie bitte nochmal.':'Error deleting user account. Please try again.',
  'Ihr Konto wurde erfolgreich gelöscht.':'Your user account has been deleted successfully.',
  'Abrufen der User Texte fehlgeschlagen.':'Failed to retrieve the user texts.',
  'Abrufen der User Wörter fehlgeschlagen.':'Failed to retrieve the user words.',
  'Login fehlgeschlagen.':'Login failed.',
  'Konto erstellen':'Create account',
  'Konto':'Account',
  'Achtung: Bei der App handelt es sich um einen Prototypen, bitte verwenden Sie für die Registrierung keine sicherheitskritischen Passwörter':'Attention: The app is a prototype, please do not use safety-critical passwords for registration',
  'Informationen':'Information',
  'Vor- und Nachname werden bei der Verifizierung angezeigt, wenn Sie einen Vorschlag abschicken':'The first and last name are displayed during verification when you submit a proposal',
  'Expertenkonto':'Experts account',
  'Für Lerntherapheuten, Linguisten etc. Stimmen von Experten erhalten bei der Verifizierung neuer Wörter ein größeres Gewicht':'For learning therapists, linguists etc. voices from experts gain more importance in verifying new words',
  'Registrieren':'Register',
  'Bitte Passwort eingeben':'Please enter password',
  'Passwort zu kurz (min. 8 Zeichen)':'Password too short (min. 8 letters)',
  'Bitte Vornamen eingeben':'Please enter first name',
  'Bitte Nachnamen eingeben':'Please enter last name',
  'Bitte machen ergängzen Sie fehlende Angaben.':'Please complete the missing information.',
  'Registrierung nicht erfolgreich.':'Registration unsuccessful.',
  'Gespeicherte Texte':'Saved texts',
  'keine Texte':'No texts',
  'Verbergen':'Hide',
  'Verwenden':'Apply',
  'Manuelle Einträge':'Manual entries',
  'keine Einträge':'No entries',
  'Manuelle Analyse':'Manual analysis',
  'Wort hinzufügen':'Adding word',
  'Noch':'Still',
  'unbekannte Wörter zu klären':'unknown words to clarify',
  'Zurück zum Text':'Back to the text',
  'Fehler beim hinzufügen des Wortes zur lokalen Datenbank.':'Error adding word to the local database.',
  'Alle unbekannten Wörter wurden geklärt.':'All the unknown words were clarified.',
  'Um bei der Verifizierung mitzuhelfen, musst Du als Benutzer eingeloggt sein':'In order to help with the verification, you must be logged in as a user',
  'Vorschlag senden':'Sending proposal',
  'Wort laden':'Loading words',
  'Im Moment gibt es keine zu verifizierende Wörter':'There are no words to verify at the moment',
  'Erneut versuchen':'Try again',
  'Noch zu verifizierende Wörter':'Words to be verified',
  'Abschicken':'Send',
  'Benutzer':'User',
  'Vorschlag konnte nicht gesendet werden.':'Suggestion could not be sent.',
  'TextAnalyse':'TextAnalysis',
  'Fehler':'Error',
  'Vorname':'First name',
  'Nachname':'Last name',
  'Vorlagenname':'Template name',
  'Zeichen':'Symbol',
  'Analysieren':'Analyze',
  'Meine Worte':'My words',
  'Meine Texte':'My texts',
  'Suchen':'Searching',
  'Fehler beim Wortsuchen. Versuchen Sie bitte nochmal.':'Error searching for word. Please try again.',
  '#de':'#en',
  'Wort':'Word',
  'Aussprache hören':'Listen to pronunciation',
  'Wörterbuchservice':'Dictionary Service',
  'Geben Sie ein Wort ein, um die Definition anzuzeigen oder die Aussprache zu hören.':'Enter a word to see its definition or to listen to its pronunciation.'
};

String switchLang(String s){
  if(isEng){
    return dict[s];
  }
  return s;
}

Url switchURL(Url current){
  //TODO switch url according to the selected language e.g. #en #de
  return current = current;
}
